version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data

  qa_space_auth:
    build:
      context: ./qa_space_auth
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - ./db:/db
    depends_on:
      - db

  qa_space:
    build:
      context: ./qa_space
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./db:/db
    depends_on:
      - db

  qa_space_api:
    build:
      context: ./qa_space_api
      dockerfile: Dockerfile
    ports:
      - 7080:7080
    volumes:
      - ./db:/db
    depends_on:
      - db