version: '3'
services:
  qa_space_auth:
    build:
      context: ./qa_space_auth
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - ./db:/db

  qa_space:
    build:
      context: ./qa_space
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./db:/db

  qa_space_api:
    build:
      context: ./qa_space_api
      dockerfile: Dockerfile
    ports:
      - 7080:7080
    volumes:
      - ./db:/db

volumes:
  db-data:
    driver: local